linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    check-shadowing: true
  misspell:
    locale: US
  nakedret:
    max-func-lines: 2
  gofumpt:
    extra-rules: true

linters:
  enable-all: true
  disable:
    - gosmopolitan
    - depguard
    - gci